# Generated by Django 5.0.3 on 2024-04-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='EVENTS',
        ),
    ]
